NerdStore/src/NerdStore.WebApp.MVC/Models/ErrorViewModel.cs
using System;

namespace NerdStore.WebApp.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Controllers/Admin/AdminProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalogo.Application.Services;
using NerdStore.Catalogo.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NerdStore.WebApp.MVC.Controllers.Admin
{
    public class AdminProdutosController  : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public AdminProdutosController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]
        [Route("admin-produtos")]
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [Route("novo-produto")]
        public async Task<IActionResult> NovoProduto()
        {
            return View(await PopularCategorias(new ProdutoViewModel()));
        }

        [Route("novo-produto")]
        [HttpPost]
        public async Task<IActionResult> NovoProduto(ProdutoViewModel produtoViewModel)
        {
            if ( !ModelState.IsValid ) return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AdicionarProduto(produtoViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarProduto(Guid id)
        {
            return View(await PopularCategorias(await _produtoAppService.ObterPorId(id)));
        }

        [HttpPost]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarPrdouto(Guid id, ProdutoViewModel produtoViewModel)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            produtoViewModel.QuantidadeEstoque = produto.QuantidadeEstoque;

            ModelState.Remove("QuantidadeEstoque");
            if ( !ModelState.IsValid ) return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AtualizarProduto(produtoViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("produtos-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id)
        {
            return View("Estoque", await _produtoAppService.ObterPorId(id));
        }

        [HttpPost]
        [Route("produtos-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id, int quantidade)
        {
            if(quantidade > 0 )
            {
                await _produtoAppService.ReporEstoque(id, quantidade);
            }
            else
            {
                await _produtoAppService.DebitarEstoque(id, quantidade);
            }

            return View("Index", await _produtoAppService.ObterTodos());
        }

        private async Task<ProdutoViewModel> PopularCategorias(ProdutoViewModel produtoViewModel)
        {

            produtoViewModel.Categorias =  await _produtoAppService.ObterCategorias();
            return produtoViewModel;
        }
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalogo.Application.Services;
using NerdStore.Core.Bus;
using NerdStore.Core.Messages.CommomMessages.Notifications;
using NerdStore.Vendas.Application.Commands;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class CarrinhoController : ControllerBase
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IMediatorHandler _mediatorHandler;

        public CarrinhoController(INotificationHandler<DomainNotification> notification,
                                  IProdutoAppService produtoAppService, 
                                  IMediatorHandler mediatorHandler) : base(notification, mediatorHandler)
        {
            _produtoAppService = produtoAppService;
            _mediatorHandler = mediatorHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("meu-carrinho")]
        public async Task<IActionResult> AdicionarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if ( produto == null ) return BadRequest();

            if(produto.QuantidadeEstoque < quantidade)
            {
                TempData["Erro"] = "Produto com estoque insuficiente";
                return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
            }

            var command = new AdicionarItemPedidoCommand(ClienteId, produto.Id, produto.Nome, quantidade, produto.Valor);
            await _mediatorHandler.EnviarComando(command);

            if(OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            //Toda vez ue eu dou um redirect eu perco o estado do request anterior
            TempData["Erros"] = ObterMensagensErro();
            return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
        }
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NerdStore.WebApp.MVC.Models;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Controllers/VitrineController.cs
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalogo.Application.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class VitrineController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public VitrineController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]
        [Route("")]
        [Route("vitrine")]
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [HttpGet]
        [Route("produto-detalhe/{id}")]
        public async Task<IActionResult> ProdutoDetalhe(Guid id)
        {
            return View(await _produtoAppService.ObterPorId(id));
        }
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Extensions/SummaryViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Messages.CommomMessages.Notifications;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NerdStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.ObterNotificacoes());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

NerdStore/src/NerdStore.WebApp.MVC/Views/AdminProdutos/AtualizarProduto.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "AtualizarProduto";
}

<h1>Editar Produto</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProduto">
            <div asp-validation-summary="All" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

NerdStore/src/NerdStore.WebApp.MVC/Views/AdminProdutos/Estoque.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel
@{
    ViewData["Title"] = "Editar Produto";
}

<div class="container">
    <div class="row">
        <div class="col-xs-4 item-photo">
            <img width="400" height="400" src="~/Images/@Model.Imagem" />
        </div>
        <div class="col-xs-5" style="border:20px solid white">
            <h3>@Model.Nome</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top:0px;">@Model.Valor.ToString("C")</h3>

            <p>Apenas @Model.QuantidadeEstoque em estoque!</p>
            <p>@Model.Descricao</p>

            <div class="section" style="padding-bottom:20px;">
                <form method="post" asp-controller="AdminProdutos" asp-action="AtualizarEstoque">
                    <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                    <input type="text" id="quantidade" name="quantidade" />
                    <button class="btn btn-info">Atualizar Estoque</button>
                </form>
            </div>
        </div>
    </div>
</div>

NerdStore/src/NerdStore.WebApp.MVC/Views/AdminProdutos/Index.cshtml
@model IEnumerable<NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Vitrine";
}
<style>
    h4 {
        font-weight: 600;
    }

    p {
        font-size: 12px;
        margin-top: 5px;
    }

    .price {
        font-size: 30px;
        margin: 0 auto;
        color: #333;
    }

    .right {
        float: right;
        border-bottom: 2px solid #4B8E4B;
    }

    .thumbnail {
        opacity: 0.70;
        -webkit-transition: all 0.5s;
        transition: all 0.5s;
    }

        .thumbnail:hover {
            opacity: 1.00;
            box-shadow: 0px 0px 10px #4bc6ff;
        }

    .line {
        margin-bottom: 5px;
    }

    @@media screen and (max-width: 770px) {
        .right {
            float: left;
            width: 100%;
        }
    }

    .product_view .modal-dialog {
        max-width: 800px;
        width: 100%;
    }

    .pre-cost {
        text-decoration: line-through;
        color: #a5a5a5;
    }

    .space-ten {
        padding: 10px 0;
    }
</style>
<div class="container">

    <h1>Administração de Produtos</h1>
    <hr />
    <div class="row">
        <a asp-controller="AdminProdutos" asp-action="NovoProduto" class="btn btn-success right">+ Adicionar Novo</a>
    </div>
    <hr />
    <div class="row">
        <!-- BEGIN PRODUCTS -->
        @{
            foreach ( var produto in Model.OrderBy(p => p.CategoriaId) )
            {
                <div class="col-md-3 col-sm-6">
                    <span class="thumbnail">
                        <img width="200" height="200" src="~/Images/@produto.Imagem" />
                        <h4>@produto.Nome</h4>
                        <p>@produto.QuantidadeEstoque em estoque</p>
                        <p>@produto.Descricao</p>
                        <p class="price">@produto.Valor.ToString("C")</p>
                        <hr class="line">
                        <div class="row">
                            <a asp-controller="AdminProdutos" asp-action="AtualizarProduto" asp-route-id="@produto.Id" class="btn btn-success right">Editar</a> &nbsp;
                            <a asp-controller="AdminProdutos" asp-action="AtualizarEstoque" asp-route-id="@produto.Id" class="btn btn-info right">Estoque</a>
                        </div>
                    </span>
                </div>
            }
        }

        <!-- END PRODUCTS -->
    </div>
</div>

NerdStore/src/NerdStore.WebApp.MVC/Views/AdminProdutos/NovoProduto.cshtml
@model NerdStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "NovoProduto";
}

<h1>Novo Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovoProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

NerdStore/src/NerdStore.WebApp.MVC/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

@if (TempData["Erro"] != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        <p>@TempData["Erro"]</p>
    </div>
}

@if (TempData["Erros"] != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        @{
            var erros = TempData["Erros"] as string[];
            foreach (var erro in erros)
            {
                <p>@erro</p>
            }
        }
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h3 id="msgRetorno">@ViewBag.Sucesso</h3>
    </div>
}